"""empty message

Revision ID: 4bf2369e2afc
Revises: a5cffa318ac2
Create Date: 2025-11-26 08:45:01.974850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf2369e2afc'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('galaxia', sa.String(length=20), nullable=False),
    sa.Column('numero_planetas', sa.Integer(), nullable=False),
    sa.Column('habitable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('fecha_suscripcion', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('apellido', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('personajes',
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('planeta_nombre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['planeta_nombre'], ['planetas.nombre'], ),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('planetas_favoritos',
    sa.Column('planeta', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['planeta'], ['planetas.nombre'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.email'], )
    )
    op.create_table('naves',
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('velocidad', sa.Integer(), nullable=False),
    sa.Column('capitan', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['capitan'], ['personajes.nombre'], ),
    sa.PrimaryKeyConstraint('nombre')
    )
    op.create_table('personajes_favoritos',
    sa.Column('personaje', sa.String(length=20), nullable=True),
    sa.Column('usuario', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['personaje'], ['personajes.nombre'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.email'], )
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('personajes_favoritos')
    op.drop_table('naves')
    op.drop_table('planetas_favoritos')
    op.drop_table('personajes')
    op.drop_table('usuario')
    op.drop_table('planetas')
    # ### end Alembic commands ###
